Fix issue where some compilers fail because of error
/usr/src/Vega-Strike-Engine-Source/engine/src/cmd/audible.h:40:30: error: no member named 'string' in namespace 'std' std::map<SoundType, std::string> defaultSoundNames;