Lib Component - connect core components (#871)
* Add Component, Reactor, EConsumer and EContainer classes

Add unit tests. 
Remove UnitCsvFactory reliance on VSFileSystem for better separation of concerns. Game doesn't build because unit tests require VSFileSystem and that pulls in half the game with it.
As this is imported from the original lib component branch by file, some stuff here is for future commits.

* Fix error C7555 in CICD on windows

use of designated initializers requires at least '/std:c++20'

* Fix bug - Implement Downgrade in Component

Reverse order of visibility in EnergyConsumer.
Make visibility modifiers explicit in EnergyContainer and Reactor.

* Connect reactor, capacitor and ftl_capacitor to engine.

* Fix multiplication warnings